apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  notification-service
      version: v1
  template:
    metadata:
      labels:
        app:  notification-service
        version: v1
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - name: notification-service
        image: eu.gcr.io/pivotal-leaf-326613/webapi:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapi-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationapi
      version: v1
  template:
    metadata:
      labels:
        app: notificationapi
        version: v1
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - name: notificationapi
        image: eu.gcr.io/pivotal-leaf-326613/webapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        # Environment variable section
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
---
apiVersion: v1
kind: Service
metadata:
  name: notificationapi-service
  labels:
    app: notificationapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  selector:
    app: notificationapi